### PR TITLE
Version 0.1

### PR DESCRIPTION
**Pull request by cberube**
Initial import

### CODE REVIEW

**Comment by nwarlen** [comment]
Is there not a case when you would want to `un-interrupt` the loop? Something like a `continue` function that sets the instance variable to `true`? Or am I missing the idea of the loop controller (totally possible)?

**Comment by nackjicholson** [comment]
:ok: :shipit:

**Comment by cberube** [comment]
@nwarlen -- I thought about adding that, and it might get put in place at some point, but generally these are intended to provide a mechanism to stop what is essentially a daemon, so the "safe way" to restart the loop is probably going to be to just restart the daemon in most cases.

**Comment by nwarlen** [comment]
:+1: :ok: :shipit:

**Pull request merged**
