### PR TITLE
Version 0.3 -- Re-implement SignalLoopController

### PR DESCRIPTION
**Pull request by cberube**

### CODE REVIEW

**Comment by nwarlen** [comment]
From comments on PHP docs, not sure of the validity or usefulness...but somethings to consider:

[For PHP >= 5.3.0, instead of declare(ticks = 1), you should now use pcntl_ signal_ dispatch().](http://php.net/manual/en/function.pcntl-signal.php)

[Remember that declaring a tick handler can become really expensive in terms of CPU cycles: Every n ticks the signal handling overhead will be executed. 
So instead of declaring tick=1, test if tick=100 can do the job. If so, you are likely to gain fivefold speed.](http://php.net/manual/en/function.pcntl-signal.php)

**Comment by cberube** [comment]
@nwarlen -- yeah, I think I'm sold on that being the right approach

**Comment by nwarlen** [comment]
:+1: :ok: :shipit:

**Comment by nackjicholson** [comment]
:ok: :shipit:

**Pull request merged**
